# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elevencli < Formula
  desc "ElevenLabs CLI — text-to-speech and sound effects from the command line"
  homepage "https://github.com/deegital/elevencli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deegital/elevencli/releases/download/v0.1.0/elevencli_0.1.0_darwin_amd64.tar.gz"
      sha256 "88cc7121f6a53a25eb5915b75b92bee72965fb33c9b0b668f5a1a1b17bdef751"

      define_method(:install) do
        bin.install "elevencli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deegital/elevencli/releases/download/v0.1.0/elevencli_0.1.0_darwin_arm64.tar.gz"
      sha256 "8d95f625b33c50c6a006eb43141d4e1bc85fc6ae1394289eb156d803cd1c5e28"

      define_method(:install) do
        bin.install "elevencli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deegital/elevencli/releases/download/v0.1.0/elevencli_0.1.0_linux_amd64.tar.gz"
      sha256 "a7be305106adfef4969adc8d2928e6064abaa9215ff0b55e535a32f6450bf280"
      define_method(:install) do
        bin.install "elevencli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deegital/elevencli/releases/download/v0.1.0/elevencli_0.1.0_linux_arm64.tar.gz"
      sha256 "efd9064342a20f8bad60981868ae026b23a6ac2ddb2786d85922a2214eec3750"
      define_method(:install) do
        bin.install "elevencli"
      end
    end
  end

  test do
    system "#{bin}/elevencli", "--version"
  end
end
