# This file was generated by GoReleaser. DO NOT EDIT.
cask "elevencli" do
  name "elevencli"
  desc "ElevenLabs CLI — text-to-speech and sound effects from the command line"
  homepage "https://github.com/deegital/elevencli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elevencli"

  on_macos do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_amd64.tar.gz"
      sha256 "887e9985617a37a93ce5f053fb4e94e1dfcb2efd5ee890cb5aaaa46bc07833ed"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_arm64.tar.gz"
      sha256 "ca7d88ad32d0c22043ae3a66174c33eedacb3b08bb66886ee7064e55cf39e1ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_amd64.tar.gz"
      sha256 "8a88087624f80428d5a37f7f9570ed1a08cdd4c191727c4200ffb1b9ee81303f"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_arm64.tar.gz"
      sha256 "040626baf9e5aae410eee659a4ffa511b6a5ef09abc792ca433ac4c8aaf0469c"
    end
  end

  # No zap stanza required
end
