# This file was generated by GoReleaser. DO NOT EDIT.
cask "elevencli" do
  name "elevencli"
  desc "ElevenLabs CLI — text-to-speech and sound effects from the command line"
  homepage "https://github.com/deegital/elevencli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elevencli"

  on_macos do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_amd64.tar.gz"
      sha256 "43ad50e53212bcc7f7b6fd1f41a95d72493be1398ed90dc03a3f28c4a4e677b2"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_arm64.tar.gz"
      sha256 "2f901f1d02d1dc51b445320f240a50e6cc375d94c77c6a857711bb9d5510bd68"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_amd64.tar.gz"
      sha256 "b65b3f3c8bbeb9f0b0805b5662e93da160b34c96840503894352e06f32cb1841"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_arm64.tar.gz"
      sha256 "1a2dba81c383a42a418dcb19c0946c28b0f0827ff827d36432b27b6d568f5dbf"
    end
  end

  # No zap stanza required
end
