# This file was generated by GoReleaser. DO NOT EDIT.
cask "elevencli" do
  name "elevencli"
  desc "ElevenLabs CLI — text-to-speech and sound effects from the command line"
  homepage "https://github.com/deegital/elevencli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elevencli"

  on_macos do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_amd64.tar.gz"
      sha256 "2bf3f69a24f4b26bb0d95a337e40a15eee8ad7efe26ea3d2dba7918468f6b52f"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_darwin_arm64.tar.gz"
      sha256 "c8317d53e711388cc20037848156b649e2aae78245764c0392c805711cd3ec6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_amd64.tar.gz"
      sha256 "3f7e0f208def5ce614c0c1881d0cb7d19d4a5c0415f3ff2c207e95673bc9796f"
    end
    on_arm do
      url "https://github.com/deegital/elevencli/releases/download/v#{version}/elevencli_#{version}_linux_arm64.tar.gz"
      sha256 "dc6789a22988ee878c3e070292116dec465a7ce01be4de7c11f0e8ce4bf4c70d"
    end
  end

  # No zap stanza required
end
